---
- name: (Debian) Clean the local repository of retrieved package files that can no longer be downloaded
  apt:
    autoclean: yes
  when: ansible_os_family == 'Debian'

- name: (Debian) Remove dependencies that are no longer required
  apt:
    autoremove: yes
  when: ansible_os_family == 'Debian'
