---
- name: (Debian) Docker set up
  block:
    - name: (Debian) Ensure old versions of Docker are not installed
      package:
        name:
          - docker
          - docker.io
          - docker-engine
          - containerd
          - runc
        state: absent

    - name: (Debian) Install Docker required system packages
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - gnupg
        update_cache: yes
        state: "{{ docker_package_state }}"

    - name: (Debian) Add Docker GPG apt key
      apt_key:
        url: "{{ docker_apt_gpg_key }}"
        state: "{{ docker_package_state }}"  

    - name: (Debian) Add Docker repository
      apt_repository:
        repo: "{{ docker_apt_repository }}"
        state: "{{ docker_package_state }}"  

    - name: (Debian) Update apt and install docker-ce
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
        update_cache: yes
        state: "{{ docker_package_state }}"  
  when: ansible_os_family == 'Debian'
  become: true
  become_user: root
