---
- name: Uninstall unnecessary packages
  apt:
    name:
      # Programming
      # Education
      # Office
      - evince
      - evince-common
      - liblibreoffice-java
      - libreoffice-base-core
      - libreoffice-calc
      - libreoffice-common
      - libreoffice-core
      - libreoffice-draw
      - libreoffice-gnome
      - libreoffice-gtk3
      - libreoffice-impress
      - libreoffice-math
      - libreoffice-ogltrans
      - libreoffice-pdfimport
      - libreoffice-style-breeze
      - libreoffice-style-colibre
      - libreoffice-style-elementary
      - libreoffice-style-yaru
      - libreoffice-writer
      # Internet
      - remmina
      - thunderbird
      - thunderbird-gnome-support
      - firefox
      - gnome-www-browser
      - transmission-gtk
      - transmission-common
      # Sound and Video
      - rhythmbox
      - vlc
      - media-player-info
      - totem
      - totem-common
      # Graphics
      - cheese
      - cheese-common
      - shotwell
      - shotwell-common
      - eog
      # Games
      - aisleriot
      - gnome-mahjongg
      - gnome-mines
      - gnome-sudoku
      # Accessories
      - gnome-calendar
      - seahorse
      - gnome-todo
      - gnome-todo-common
      - gnome-calculator
      # System
      - deja-dup
      # Help
      - gnome-help
    update_cache: yes
    state: absent

- name: Install required packages
  apt:
    name:
      - auditd
      - ufw
    update_cache: yes
    state: present

- name: Ensure shh is started and enabled at boot
  service:
    name: ssh
    enabled: true
