---
- name: Install services/apps
  block:
    # Copy manifests
    - name: Copy services and apps to master
      copy:
        src: "../config/k8s/services"
        dest: "/home/{{ user }}"
    # ArgoCD
    - name: Install ArgoCD
      command: "{{ item }}"
      with_items:
        - "kubectl apply -f /home/{{ user }}/services/argocd/namespace.yaml"
        - "kubectl apply -n argocd -f /home/{{ user }}/services/argocd/install.yaml"
      become: false
      when: argocd_install | bool
    # Ingress nginx
    - name: Install Nginx
      command: "{{ item }}"
      with_items:
        - "kubectl apply -f /home/{{ user }}/services/nginx/deploy.yaml"
      become: false
      when: nginx_install | bool
  when: inventory_hostname == "{{ k8s_master_name }}"
