---
- hosts: all
  remote_user: "{{ user  }}"
  become: yes
  vars_files:
    - "../vars/docker.yaml"
    - "../vars/k8s.yaml"
    - "../vars/host-config.yaml"
  tasks:
    - name: Configure all machines
      include_tasks: ../tasks/configure-hosts.yaml

    - name: Provision and benchmark Docker and Kubernetes
      include_tasks: ../tasks/main.yaml

    - name: Clear packages on all machines
      include_tasks: ../tasks/autoremove.yaml
